from faker.providers import BaseProvider


class FakeGroceryProvider(BaseProvider):
    classes = (
        "Bio",
        "Budget",
        "Premium",
        "TK",
    )

    products = (
        "Äpfel Gala",
        "Äpfel Jazz",
        "Äpfel Braeburn",
        "Äpfel Boskoop",
        "Äpfel Greenstar",
        "Avocado",
        "Brombeeren",
        "Erdbeeren",
        "Johannisbeeren",
        "Heidelbeeren",
        "Himbeeren",
        "Beerenmischung",
        "Beluga-Linsen",
        "Berglinsen",
        "Teller-Linsen",
        "Lager Bier",
        "Pale Ale",
        "Pils",
        "Dunkles Bier",
        "Craftbeer",
        "Eier S",
        "Eier M",
        "Eier L",
        "Wachteleier",
        "Poulet ganz",
        "Pouletbrust",
        "Poulet Filet",
        "Pouletschenkel",
        "Pouletflügel",
        "Poulet Würfel",
        "Poulet Geschnetzeltes",
        "Poulet Hackfleisch",
        "Birnen Williams",
        "Birnen Kaiser",
        "Edamame",
        "Kidneybohnen",
        "Schwarze Bohnen",
        "Baguette",
        "Brezel klein",
        "Brezel gross",
        "Ruchbrot",
        "Sauerteigbrot",
        "Schwarzbrot",
        "Ciabatta",
        "Vollkornbrot",
        "Butter",
        "Bratbutter",
        "Champignons Braun",
        "Champignons Weiss",
        "Kräuter-Seitling",
        "Morcheln",
        "Steinpilz",
        "Pfifferlinge",
        "Butterröhrling",
        "Spinat",
        "Rucola",
        "Kopfsalat",
        "Feldsalat",
        "Eisbergsalat",
        "Chicorée",
        "Chinakohl",
        "Apfelessig",
        "Weissweinessig",
        "Aceto balsamico",
        "Branntweinessig",
        "Tafelessig",
        "Olivenöl",
        "Sonnenblumenöl",
        "Rapsöl",
        "Sesamöl",
        "Erdnussöl",
        "Seelachsfilet MSC",
        "Dorschfilet ASC",
        "Rotzungenfilet MSC",
        "Thunfisch ASC",
        "Eglifilet MSC",
        "Schwertfisch ASC",
        "Schweisfilet",
        "Schweisragout",
        "Schweinsteak",
        "Schweineschnitzel",
        "Schweinsgeschnetzeltes",
        "Schweinehackfleisch",
        "Rindsfilet",
        "Rindsragout",
        "Rindssteak",
        "Rindsschnitzel",
        "Rindsgeschnetzeltes",
        "Rindshackfleisch",
        "Chilipulver",
        "Oregano",
        "Schwarzer Pfeffer",
        "Weisser Pfeffer",
        "Grüner Pfeffer",
        "Petersilie glatt",
        "Petersilie gekraust",
        "Kardamom",
        "Kreuzkümmel",
        "Paprika edelsüs",
        "Paprika geräuchert",
        "Paprika rosenscharf",
        "Thymian",
        "Nelken",
        "Kurkuma",
        "Koreander",
        "Curry mild",
        "Curry scharf",
        "Cayennepfeffer",
        "Anis",
        "Rosmarin",
        "Zimt",
        "Safran",
        "Gurken",
        "Milch",
        "Hafermilch",
        "Sojamilch",
        "Honig",
        "Blütenhonig",
        "Waldhonig",
        "Ingwer",
        "Knoblauch",
        "Zwiebeln",
        "Kartoffeln mehlig",
        "Kartoffeln fest",
        "Süsskartoffeln",
        "Karotten",
        "Meerrettich",
        "Staudensellerie",
        "Knollensellerie",
        "Basilikum",
        "Bergkäse",
        "Alpenkäse",
        "Mozarella",
        "Weichkäse",
        "Frischkäse",
        "Butternut Kürbis",
        "Spaghetti Kürbis",
        "Knirps Kürbis",
        "Lammfilet",
        "Halbes Kaninchen",
        "Wassermelone",
        "Honigmelone",
        "Cantaloupe",
        "Penne",
        "Spaghetti",
        "Fusilli",
        "Farfalle",
        "Hörnli",
        "Gnocchi",
        "Haselnüsse",
        "Walnüsse",
        "Mandeln",
        "Cashew",
        "Pinienkerne",
        "Orangen",
        "Blutorangen",
        "Grapefruit",
        "Clementinen",
        "Mandarinen",
        "Zitrone",
        "Limette",
        "Peperoni Rot",
        "Peperoni Orange",
        "Peperoni Gelb",
        "Pepperoncini",
        "Chillies",
        "Cherrytomaten",
        "San-Marzano-Tomaten",
        "Rispentomaten",
        "Langkornreis",
        "Jasminreis",
        "Basmatireis",
        "Wildreis",
        "Schwarzer Reis",
        "Rotwein",
        "Weisswein",
        "Sake",
        "Whiskey",
        "Gin",
        "Rum",
        "Salz",
        "Rohzucker",
        "Kristallzucker",
    )

    amounts = (
        "0.33",
        "0.5",
        "0.75",
        "1",
        "1.5",
        "4",
        "6",
        "8",
        "10",
        "20",
        "25",
        "30",
        "33",
        "40",
        "50",
        "60",
        "70",
        "75",
        "80",
        "90",
        "100",
        "200",
        "300",
        "400",
        "500",
        "600",
        "700",
        "800",
        "900",
        "6x50",
        "6x33",
        "24x50",
        "24x33",
    )

    units = (
        "cl",
        "dl",
        "l",
        "g",
        "kg",
    )

    def grocery(self) -> str:
        parts = []

        # add class with 10% probability
        if self.random_int(0, 9) >= 9:
            parts.append(self.random_element(self.classes))

        parts.append(self.random_element(self.products))

        # add fixed amount with 5% probability
        if self.random_int(0, 19) >= 19:
            parts.append(self.random_element(self.amounts))
            parts.append(self.random_element(self.units))

        return ' '.join(parts)
